### ISSUE TITLE
Warning in UAV-Processing-Toolbox Demo

### ISSUE THREAD

**Issue by allisonpenko** [Coastal-Imaging-Research-Network/UAV-Processing-Toolbox#15]
I get the following warning when running both sampleAerielleVideoDemo.m and sampleAerielleVideoDemoPIX.m. All output seems ok otherwise.

> Warning: DB has no station Aerielle, assuming GMT 
> In argusFilename (line 125)
>  In printAndSaveImageProducts (line 48)
>  In sampleAerielleVideoDemoPIX (line 221)

**Comment by RobHolman** [comment]
This is fine.  I used argusFilename which creates pretty useful file names but I think it looks up the station in the database or something.   Without that info it just defaults to a GMT time zone.  We could make it more beautiful but it isn’t harmful.

Rob Holman
SECNAV/CNO Chair in Oceanography

104 Ocean Admin Bldg.
CEOAS-OSU
Corvallis, Oregon, USA 97331-5503
ph: 1-541-737-2914
holman@coas.oregonstate.edu
http://cil-www.coas.oregonstate.edu
