### ISSUE TITLE
New name

### ISSUE THREAD

**Issue by mpalmsten** [Coastal-Imaging-Research-Network/UAV-Processing-Toolbox#2]
Should this repository be renames something like UAV and single camera processing codes, since it can be used for both stationary and non-stationary camera? I think that people might not know from the name that the toolbox can be used for stationary too (I didn't until Rob pointed it out to me).

**Comment by jstanleyx** [comment]
Hello? Hello? I'm looking for a good Italian restaurant in the Eugene area. Can anyone help me? Hello? Is this the Eugene restaurant wiki?

Where's my glasses?

**Comment by mpalmsten** [comment]
This is not the Eugene restaurant wiki or the lost glasses wiki @jstanleyx
