### ISSUE TITLE
Caltech calibResults to Argus lcp format

### ISSUE THREAD

**Issue by SRHarrison** [Coastal-Imaging-Research-Network/UAV-Processing-Toolbox#38]
Does anyone have a tool that takes the Calib_Results.mat output from Caltech lens calibration and puts it into the format used as lcp data in Argus format?

If not, I'd like to propose that a function be created and added to the master.

**Comment by allisonpenko** [comment]
I just created a pull request for a script to save the Caltech toolbox output in lcp format. It's quick and simple - feel free to change/replace. We probably want to change the Demo and Input files to read a user specified lcp.mat file instead of it calling from a hard coded distortion file.
