### ISSUE TITLE
Error due to space, . , or - in path

### ISSUE THREAD

**Issue by mpalmsten** [Coastal-Imaging-Research-Network/UAV-Processing-Toolbox#43]
sampleAerielleDemo.m has an crashes when you try to load in images where there is a space, dot, or dash in the path where the images are stored. We should figure out how to handle spaces and special characters in the path.

**Comment by sebpitman** [comment]
It needs a test, but try replacing lines 24-31 with the following;

```
if isempty(inds)
    eval(['insts = ' inputs.instsFn ';']);
else
    p = pwd; eval(['cd ' '''' inputs.instsFn(1:inds(end)) ''''])
    eval(['insts = ' inputs.instsFn(inds(end)+1:end) ';']);
    eval(['cd ' '''' p '''']); clear p
end
```
The introduction of the quadruple apostrophes makes the text after cd a string, rather than a variable and should be sufficient to deal with the problem.

**Comment by mpalmsten** [comment]
Hey Seb, can you please push your changes to the development branch and do a pull request so we can merge your fix?

**Comment by hokiespurs** [comment]
@mpalmsten, @sebpitman, Would the built in function "fileparts" help?
```matlab
[~, insts, ~]=fileparts(inputs.instsFn);
````

Also, rather than using the sometimes dangerous 'eval' command, you can call cd with the parameter as a variable using parenthesis rather than a space:
```matlab
p = pwd;
%eval syntax
eval(['cd ' '''' p '''']);
%parenthesis syntax
cd(p);
```

**Comment by mpalmsten** [comment]
Issue was fixed!
